# Generated by Django 5.0.6 on 2024-05-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='donde',
            new_name='done',
        ),
    ]
